spring:
  application:
    name: noticerti

  datasource:
    url: jdbc:h2:file:./h2-database
    driver-class-name: org.h2.Driver
    username: sa
    password: 1234

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
